//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanMyTripDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingDetail
    {
        public int BookingId { get; set; }
        public Nullable<int> Roomid { get; set; }
        public string BookedFor { get; set; }
        public Nullable<System.DateTime> BookedFrom { get; set; }
        public Nullable<System.DateTime> BookedTo { get; set; }
        public Nullable<int> NoOfAdults { get; set; }
        public Nullable<int> NoOfChildren { get; set; }
        public Nullable<int> Amount { get; set; }
    
        public virtual RoomDetail RoomDetail { get; set; }
        public virtual RoomDetail RoomDetail1 { get; set; }
        public virtual RoomDetail RoomDetail2 { get; set; }
        public virtual RoomDetail RoomDetail3 { get; set; }
    }
}
