//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlanMyTripDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Itenary
    {
        public int ReservationId { get; set; }
        public Nullable<int> PassengerId { get; set; }
        public Nullable<int> ScheduleId { get; set; }
    
        public virtual FlightSchedule FlightSchedule { get; set; }
        public virtual FlightSchedule FlightSchedule1 { get; set; }
        public virtual FlightSchedule FlightSchedule2 { get; set; }
        public virtual FlightSchedule FlightSchedule3 { get; set; }
        public virtual Passenger Passenger { get; set; }
        public virtual Passenger Passenger1 { get; set; }
        public virtual Passenger Passenger2 { get; set; }
        public virtual Passenger Passenger3 { get; set; }
    }
}
